### ISSUE TITLE
`libsass` bindings not found errors

### ISSUE THREAD

**Issue by vedant1811** [shaialon/ember-admin-dashboards#12]
After installing, I try to run `ember server` but I get the error: ``libsass` bindings not found. Try reinstalling `node-sass`` 

While nomboming (and also, otherwise) I get this:

    vedant@vedant-Galago-UltraPro:~/rails/ember-admin-dashboards$ npm rebuild node-sass

    > node-sass@2.1.1 install /home/vedant/rails/ember-admin-dashboards/node_modules/node-sass
    > node scripts/install.js

    > node-sass@2.1.1 postinstall /home/vedant/rails/ember-admin-dashboards/node_modules/node-sass
    > node scripts/build.js

    module.js:341
        throw err;
        ^

    Error: Cannot find module '/home/vedant/rails/ember-admin-dashboards/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.Module._load (module.js:290:25)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:140:18)
        at node.js:1001:3
    Build failed
    node-sass@2.1.1 /home/vedant/rails/ember-admin-dashboards/node_modules/node-sass

Not sure if this is just a local issue but right now I'm pretty much stuck :(

I am using npm 3.8.1, node 5.6.0

**Comment by jwright04** [comment]
I'm running into this issue as well, haven't figured out a way around it.
